### ISSUE TITLE
win_dns_client is not idempotent

### ISSUE THREAD

**Issue by lod** [ansible-collections/community.windows#101]
Using Ansible 2.9.9 - Debian

```
  win_dns_client:
    adapter_names: Ethernet
    ipv4_addresses: []
```

This consistently reports as changed, even on multiple runs.

I would expect the task to be idempotent, future calls should not change the system.

**Comment by jborean93** [comment]
This was reported with https://github.com/ansible/ansible/issues/66450 and subsequently fixed with https://github.com/ansible/ansible/pull/66451. The changes are in this collection but it was never backported to stable-2.9 hence why in the current Ansible releases the behaviour is still there.

**Comment by lod** [comment]
Fantastic, sorry I didn't see that
