### ISSUE TITLE
win_domain_user absent fails on non-leaf objects

### ISSUE THREAD

**Issue by Akasurde** [ansible-collections/community.windows#106]
_From @ntsapek on Jul 01, 2020 12:39_

##### SUMMARY

We have a scheduled job that based on some date calculations deletes disabled AD users after 180 days. Recently we realized that the task occasionally fails with the following message:
`"msg": "The directory service can perform the requested operation only on a leaf object"`

Apparently, any AD User that at some point has enabled _ExchangeActiveSync_ in a mobile device, is turned into an AD Object that contains children. 
![image](https://user-images.githubusercontent.com/13422251/86243862-59dfe780-bba7-11ea-8471-ef2b34c40f39.png)

As a workaround, we stopped using the win_domain_user module and put in place a Powershell script that performs the necessary _-Recursive_ action:
`Get-ADUser -Identity "{{ item.value.name }}" | Remove-ADObject -Recursive -Confirm:$false`

It'd be nice though, to be able to perform this operation using the `win_domain_user` module.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`win_domain_user`
##### ANSIBLE VERSION

```paste below
ansible 2.8.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]
```

##### CONFIGURATION

```paste below
-
```

##### OS / ENVIRONMENT

target OS: Windows Server 2012
host OS: Debian 9

##### STEPS TO REPRODUCE

Try setting an absent state at any AD user that is not a leaf object. 

```yaml
state: absent
```

##### ACTUAL RESULTS

```paste below

```

_Copied from original issue: ansible/ansible#70410_

**Comment by jborean93** [comment]
The `win_domain_user` module has been deprecated by https://github.com/ansible-collections/community.windows/pull/516 in favour of [microsoft.ad.user](https://docs.ansible.com/ansible/devel/collections/microsoft/ad/user_module.html#ansible-collections-microsoft-ad-user-module). See the [migration guide](https://docs.ansible.com/ansible/devel/collections/microsoft/ad/docsite/guide_migration.html#module-win-domain-user) for more info on how to change your code to use the newer module.

The code used to delete AD objects should correctly handle this scenario

https://github.com/ansible-collections/microsoft.ad/blob/486f7848899ea419c10486947632f2e73db35e69/plugins/module_utils/_ADObject.psm1#L884-L893

If this is still a problem please report an issue on [microsoft.ad](https://github.com/ansible-collections/microsoft.ad) as that is where the `microsoft.ad.user` (and other AD modules) now live.
