### ISSUE TITLE
win_partition: Disk resizing is not working

### ISSUE THREAD

**Issue by Udayendu** [ansible-collections/community.windows#113]
##### SUMMARY
`win_partition`  is not able to resize the HDD after adding more space to it.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
- win_partition

##### ANSIBLE VERSION
```
# pip3 show ansible
Name: ansible
Version: 2.9.10
Summary: Radically simple IT automation
Home-page: https://ansible.com/
Author: Ansible, Inc.
Author-email: info@ansible.com
License: GPLv3+
Location: /usr/local/lib/python3.8/dist-packages
Requires: PyYAML, jinja2, cryptography
Required-by:

# pip3 show pywinrm
Name: pywinrm
Version: 0.4.1
Summary: Python library for Windows Remote Management
Home-page: http://github.com/diyan/pywinrm/
Author: Alexey Diyan
Author-email: alexey.diyan@gmail.com
License: MIT license
Location: /usr/local/lib/python3.8/dist-packages
Requires: requests, requests-ntlm, six, xmltodict
Required-by:

# snap list powershell
Name        Version  Rev  Tracking       Publisher              Notes
powershell  7.0.2    132  latest/stable  microsoft-powershell✓  classic
```

##### CONFIGURATION
```
- name: Extend the C drive to the max space
  win_partition:
      partition_size: -1
      partition_number: 0
      disk_number: 0
```

##### OS / ENVIRONMENT
- Ubuntu 20.04 LTS
- Powershell 7.0.2
- ansible 2.9.10
- PyWinRM 0.4.1

##### STEPS TO REPRODUCE
- Deploy a windows 2016 VM with a single disk
- Keep the VM in shutdown state
- Expand the dist from VMware side from 150GB to 200GB
- Try to extend the C drive side in the
- Even tried after starting the vm but still not working

##### EXPECTED RESULTS
It should perform the disk resize from current size to full size.

##### ACTUAL RESULTS
- When powershell module is not installed, getting the following error:

```
TASK [Extend the C drive to the max space] ********************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "/bin/sh: 1: powershell: not found\n", "module_stdout": "", "msg": "The module failed to execute correctly, you probably need to set the interpreter.\nSee stdout/stderr for the exact error", "rc": 127}
```

-  When powershell module is installed, its failing with the following error message even tough winrm is installed in the provision server:

```
TASK [Extend the C drive to the max space] ********************************************************************************************************************************************************************
task path: /root/Windows/win-deploy.yaml:70
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir /root/.ansible/tmp/ansible-tmp-1594786286.5379546-20691-231008766937673 && echo ansible-tmp-1594786286.5379546-20691-46-20691-231008766937673 `" ) && sleep 0'
Using module file /usr/local/lib/python3.8/dist-packages/ansible/modules/windows/win_partition.ps1
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-20477s4z5k8am/tmpel7rp7_j TO /root/.ansible/tmp/ansible-tmp-1594786286.5379546-20691-231008766937673/AnsiballZ_win_partition.ps1
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1594786286.5379546-20691-231008766937673/ /root/.ansible/tmp/ansible-tmp-1594786286.5379546-20691-231008766937673/AnsiballZ_win_partition
<127.0.0.1> EXEC /bin/sh -c 'powershell /root/.ansible/tmp/ansible-tmp-1594786286.5379546-20691-231008766937673/AnsiballZ_win_partition.ps1 && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1594786286.5379546-20691-231008766937673/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "\u001b[91mParserError: \u001b[0m/root/.ansible/tmp/ansible-tmp-1594786286.5379546-20691-231008766937673/AnsiballZ_win_partition.ps1:151\n\u001b[96mLine |\n\u001b[96m 151 | \u001b[0m \u0NoZWxsCgojIENvcHlyaWdodDogKGMpIDIwMTg …\n\u001b[96m     | \u001b[91m ~\n\u001b[91m\u001b[96m     | \u001b[91munexpected token '\u0000', expected 'begin', 'process', 'end', or\n\u001b[96m     | \u001b[91m'dyn
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Comment by jborean93** [comment]
As I mentioned in https://github.com/ansible/ansible/issues/70643 this isn't a problem with the win_partition module. Please go through the mailing list or IRC channel to get some help. The cause of your problem is that you are executing a PowerShell module using the local connection plugin which will be a Linux environment. This will not work, you typically need to use the winrm connection plugin and target a Windows host for this to work.

Issues on this repo should be used for actual bugs in the collection whereas this is a configuration problem.

**Comment by Udayendu** [comment]
>>> This will not work, you typically need to use the winrm connection plugin and target a Windows host for this to work.

       In the documentation no where these things are mentioned clearly with an example. How you are expecting some one to understand the actual execution flow ? Is there any other place were I can get some reference.

**Comment by jborean93** [comment]
As I said, go to the mailing list or IRC to ask for help. You need to provide more info such as the inventory setup, how you are expecting to run the hosts. These are all user questions and not bugs which is exactly what the mailing list and IRC are for. as for how to configure WinRM we have plenty of guides in our docs, the main one when it comes to setting Ansible to use WinRM would be located at https://docs.ansible.com/ansible/latest/user_guide/windows_winrm.html.

**Comment by Udayendu** [comment]
Finally able to connect to the windows guest after doing some setting change in the WinRM inside the guest but 'win_partition' is creating a new partition instead of extending one:

# cat ../inventory
[windows]
xxx.xxx.xxx.xxx

[windows:vars]
ansible_connection=winrm
ansible_user=Administrator
ansible_password=xxxxxxxxxx
ansible_winrm_transport=basic
ansible_winrm_server_cert_validation=ignore
ansible_port=5985

# cat disk.yaml
---
- name: Extend the C drive to the max space
  hosts: "{{ target }}"
  gather_facts: false
  connection: winrm

  tasks:
    - name: Disk extension
      win_partition:
        state: present
        partition_size: -1
        partition_number: 0
        disk_number: 0

# ansible-playbook  -i ../inventory -e target=windows disk.yaml

PLAY [Extend the C drive to the max space] ***************************************************************************************************************************************************************************************************************

TASK [Disk extension] ***********************************************************************************************************************************************************************************************************************************
changed: [xxx.xxx.xxx.xxx]

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************************
xxx.xxx.xxx.xxx              : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

**Comment by Udayendu** [comment]
# Before change
![image](https://user-images.githubusercontent.com/1809177/87530652-3e4c0500-c6ae-11ea-8ea2-363f70b61b3a.png)

# After change
![image](https://user-images.githubusercontent.com/1809177/87530709-5459c580-c6ae-11ea-86f0-fa88bb5cda3c.png)

**Comment by Udayendu** [comment]
Able to fix this. I was using the wrong partition number.

The new playbook is:

$ cat  disk.yaml
```
---
- name: Extend the C drive to the max space
  hosts: "{{ target }}"
  gather_facts: false
  connection: winrm

  tasks:
    - name: Disk extension
      win_partition:
        state: present
        partition_size: -1
        disk_number: 0
        partition_number: 2
```

**Comment by gouthamkamre68** [comment]
How to shrink  C drive as i see above  code only for extend the drive.
