### ISSUE TITLE
win_partition: Not handling the disk initialization

### ISSUE THREAD

**Issue by Udayendu** [ansible-collections/community.windows#115]
##### SUMMARY
Currently **win_partition** is not able to handle the disk initialization. And without disk initialization, disk partition cant be done. Hence required this functionality.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
- win_partition

##### ADDITIONAL INFORMATION
In windows vm to create a partition the flow is:
- Attach the new HDD to the vm
- Initialize the disk
- Partition the disk with Drive Letter and Label
- Format the disk

Command to initialize disk from powershell:
```
PS C:\> Initialize-Disk -Number 1 -PartitionStyle MBR
PS C:\> Initialize-Disk -Number 2 -PartitionStyle MBR
```

NOTE: Here 1 and 2 are my E and F drive as C is for OS and D is for CD-ROM by default.

**Comment by sakar97** [comment]
So, Including that feature in the same module will work, or creating a new module is a better option? where the user can initialize or clear the disk.

**Comment by Udayendu** [comment]
> So, Including that feature in the same module will work, or creating a new module is a better option? where the user can initialize or clear the disk.

    I think we can include in this module as its already doing the two activities but just the disk initialization is missing.

**Comment by jborean93** [comment]
Not sure how I missed it before but there was a module added in the 2.10 dev cycle [win_initialize_disk](https://github.com/ansible-collections/community.windows/blob/main/docs/community.windows.win_initialize_disk_module.rst) that can do this for you. Because we have a module for this I am closing the issue.
