### ISSUE TITLE
Add NS record to win_dns_record module

### ISSUE THREAD

**Issue by git-cgallagher** [ansible-collections/community.windows#123]
It would be nice to manage NS records with the win_dns_record module.  It's worth noting that Microsoft's own cmdlets do not follow the same syntax for this type of record and is parameterized with a **-NS**

**Comment by joezollo** [comment]
Agreed. Would love to see this added.

**Comment by jborean93** [comment]
Has been added with https://github.com/ansible-collections/community.windows/pull/131 and will be included in the next release (1.1.0) of this collection.
