### ISSUE TITLE
How To Powershell Windows Server 2012 r2, copy domain profile active firewall rules an paste to public firewall rules

### ISSUE THREAD

**Issue by espaay** [ansible-collections/community.windows#164]
Please raise issues via the [new interface](https://github.com/ansible/ansible/issues/new/choose)

**Comment by jborean93** [comment]
You cannot copy an existing rule using any of our modules. You will have to define your own rule with [win_firewall_rule](https://docs.ansible.com/ansible/latest/collections/community/windows/win_firewall_rule_module.html) based on the settings your require. There may even be a rule for the public profile that is already defined and you just need to enable.

Adding support for copying a rule is not something we wish to add as the module itself is already quite complicated. In the future you might get more prompt responses by going to our mailing list or IRC at

   * IRC: #ansible or #ansible-windows on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by espaay** [comment]
Thanks for the response, I will follow your instructions.


Respectfully,

Edward Spaay
Senior Engineer, Infrastructure Configuration

ICMA-RC
777 North Capitol St., NE
Washington, DC 20002
W: 202-682-6494
C: 443-939-2764
E: espaay@icmarc.org<mailto:espaay@icmarc.org>

BUILDING PUBLIC SECTOR
RETIREMENT SECURITY
