### ISSUE TITLE
Extend win_domain_computer adding managedBy parameter

### ISSUE THREAD

**Issue by goshansp** [ansible-collections/community.windows#173]
##### SUMMARY
Current **win_domain_computer** could be extended to  allow for "managedBy" parameter beeing populated for AD-Computer-Objects (i.e. New-ADComputer). As reference, **win_domain_group** has the said feature and properly populates managedBy. Perhabs a simple copy-paste will implement this feature idea. This feature would improve the provisioning process  by eliminating manual tasks.

Example from win_domain_group: https://github.com/ansible-collections/community.windows/search?q=managedBy

##### ISSUE TYPE
Feature Idea

##### Proposed Parameter Name:
win_domain_computer ->  managed_by
  
##### ADDITIONAL INFORMATION
https://docs.microsoft.com/en-us/powershell/module/addsadministration/new-adcomputer?view=win10-ps

### To be changed win_domain_computer
https://github.com/ansible-collections/community.windows/blob/main/plugins/modules/win_domain_computer.ps1
https://github.com/ansible-collections/community.windows/blob/main/plugins/modules/win_domain_computer.py

### Example win_domain_group
https://github.com/ansible-collections/community.windows/blob/main/plugins/modules/win_domain_group.ps1
https://github.com/ansible-collections/community.windows/blob/main/plugins/modules/win_domain_group.py

**Comment by goshansp** [comment]
Dear @sbaerlocher
Thank you for offering to implement this. Our customer has agreed and will be providing the funds as discussed. Please let us know as soon as you have an ETA. Cheers!

**Comment by sbaerlocher** [comment]
@goshansp I have made you times 1 pre-release, can you test this locally with you to see if it delivers the desired result?

**Comment by briantist** [comment]
@sbaerlocher is there a PR you can link to?

**Comment by sbaerlocher** [comment]
@briantist yes, PR #185

**Comment by goshansp** [comment]
the PR has been merged and the feature was released with 2.10.6 - we've just deployed to production. outstanding work gentlemen! thank you.
