### ISSUE TITLE
need win_zip or win_archive module 

### ISSUE THREAD

**Issue by sugitk** [ansible-collections/community.windows#235]
##### SUMMARY

We cannot create a zip archive on Windows

##### ISSUE TYPE
- Feature Idea

##### ADDITIONAL INFORMATION

```yaml

```

**Comment by mariairisong** [comment]
Hi, looking for win_zip for ansible 2.9, similar to the module in ansible 2.8. Thanks! While win_shell works, we're looking for this module so playbooks are the same across different ansible servers.

**Comment by hiyokotaisa** [comment]
New module has been merged so I think we can close this issue
