### ISSUE TITLE
define the keyboard layout

### ISSUE THREAD

**Issue by rgl** [ansible-collections/community.windows#255]
##### SUMMARY

I would like to be able to define the keyboard layout using a module.

It should also be able to set the windows login screen keyboard layout (maybe using another module).

##### ISSUE TYPE

- Feature Idea

##### COMPONENT NAME

win_keyboard

##### ADDITIONAL INFORMATION

For the current user, this could be done in PowerShell with `Set-WinUserLanguageList 'pt-PT','en-US' -Force`.

For setting the login screen keyboard layout, I have no working solution (calling `Set-WinUserLanguageList` from the `SYSTEM` account in a scheduled task does not seem to do the trick; nor simply playing with `HKEY_CURRENT_USER\Keyboard Layout\Preload`). Maybe some of you known how to do it? :-)

**Comment by darthwalsh** [comment]
Needed this today. This setting could be an option in `win_region`?

**Comment by myllynen** [comment]
Allowing to configure input (keyboard) would be nice. Copying settings to Welcome screen will hopefully get easier once Copy-UserInternationalSettingsToSystem becomes available:

https://docs.microsoft.com/en-us/powershell/module/international/copy-userinternationalsettingstosystem

Currently this seems hard to do reliably, however there are also reports from users how Welcome screen keyboard occasionally get changed by the system so this cmdlet by itself may not solve all the related issues. An example of a less than month old description of the changing keyboard is here: https://techcommunity.microsoft.com/t5/windows-servicing/wrong-keyboard-layout-at-login-screen/m-p/3260209.

**Comment by jborean93** [comment]
As per the README https://github.com/ansible-collections/community.windows#contributing-to-this-collection this collection is currently only accepting bugfixes or features to existing modules.
