### ISSUE TITLE
Add management of AD field "altsecurityidentities"  to win_domain_user module

### ISSUE THREAD

**Issue by jborean93** [ansible-collections/community.windows#26]
_From @shakalandy on Oct 26, 2018 09:18_

##### SUMMARY
As an automation guy i want to make sure that the complete user-management stuff is done by ansible.
Currently we and a lot of other companies use Microsoft Active Directory as single source of truth regarding user accounts. That's why we are using it for ssh authentication via SSSD.
Due to security reasons we don't want to rely on the AD password, but stick to SSH Key Authentication.
This can be easily done in sssd, you just need to point to the proper field in active directory. 
Is is quite common to use the field field "altsecurityidentities" for that purpose, because AD schema manipulation should be avoided.

##### ANSIBLE VERSION
2.7

##### ISSUE TYPE
Enhance the module win_domain_user in a way that you can manage the users ssh public key in the field "altsecurityidentities" via ansible. 

##### COMPONENT NAME
module: win_domain_user

##### ADDITIONAL INFORMATION
see summary

```---
- hosts: win-ad
#  gather_facts: false

  tasks:
    - name: add key to ad user
      win_domain_user:
        domain_username: remoteldapuser
        domain_password: password
        domain_server: domain.example.com
        name: jwhitehurst
        path: "OU=Linux,OU=Permissions,OU=Security,OU=_Global,DC=domain,DC=example,DC=com"
        altsecurityidentities: "ssh-rsa 1yc2EAAAABIwAAAQEAklOUpkDHrfHY17SbrmTIpNLTGK9Tjom/BWDSU
GPl+nafzlHDTYW7hdI4yZ5ew18JH4JW9jbhUFrviQzM7xlELEVf4h9lFX5QVkbPppSwg0cda3
Pbv7kOdJ/MTyBlWXFCR+HAo3FX jwhitehurst"

```

_Copied from original issue: ansible/ansible#47653_

**Comment by jborean93** [comment]
_From @shakalandy on Oct 26, 2018 10:06_

added ansible version, component name was already there. Thanks @ansibot

**Comment by Slm0n87** [comment]
We do exactly this since several weeks - setting ssh-public-keys into the altsecurityidentities.  
You just have to use the "attributes" key:
```
tasks:
    - name: add key to ad user
      win_domain_user:
        attributes:
          altSecurityIdentities: "ssh-rsa ...."
```

**Comment by jborean93** [comment]
The `win_domain_user` module has been deprecated by https://github.com/ansible-collections/community.windows/pull/516 in favour of [microsoft.ad.user](https://docs.ansible.com/ansible/devel/collections/microsoft/ad/user_module.html#ansible-collections-microsoft-ad-user-module). See the [migration guide](https://docs.ansible.com/ansible/devel/collections/microsoft/ad/docsite/guide_migration.html#module-win-domain-user) for more info on how to change your code to use the newer module.

Using the `attributes` key is what is needed here, there are no plans on exposing every attribute as a specific option.
