### ISSUE TITLE
please assist, How/where to find the default ansible version available with AWX 19.2.2 ?

### ISSUE THREAD

**Issue by unixplex** [ansible-collections/community.windows#267]
please assist, How/where to find the default ansible version available on AWX 19.2.2 ?

**Comment by jborean93** [comment]
List Information
================

Hi!

This isn't a question about `community.windows`, you should direct your question to the standard mailing list and IRC for help here.

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on `irc.libera.chat <https://libera.chat/>`_
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
