### ISSUE TITLE
Setting username/password with win_service results in error "Logon failure: the user has not been granted the requested logon type at this computer"

### ISSUE THREAD

**Issue by nre-ableton** [ansible-collections/community.windows#290]
##### SUMMARY

Related to #227, I am trying to now set the service's username/password with `win_service`, since it appears that the `user` argument to `win_nssm` is to be removed.

My original task to do this task was:

```yaml
- name: Set service user
  win_shell: >
    nssm.exe set \
      '{{ my_service_name }}' \
      ObjectName .\\{{ my_username }} {{ my_password }}
```

I tried changing this to:

```yaml
- name: Set service user
  win_service:
    name: "{{ my_service_name }}"
    username: "{{ my_username }}"
    password: "{{ my_password }}"
```

Although the previous command worked fine, the `win_service` command fails when the service attempts to start in a later task. Looking at the Windows Event Viewer, I see the error message "Logon failure: the user has not been granted the requested logon type at this computer".

What logon type is required for this command to work? Clearly, it worked before when using NSSM.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

* `win_service`

##### ANSIBLE VERSION

```paste below
ansible 2.10.13
  config file = /home/nre/<redacted>/ansible.cfg
  configured module search path = ['/home/nre/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/nre/.local/lib/python3.9/site-packages/ansible
  executable location = /home/nre/.local/bin/ansible
  python version = 3.9.5 (default, May 11 2021, 08:20:37) [GCC 10.3.0]
```

##### COLLECTION VERSION

Erm, `ansible-galaxy community list` throws an error, but it's version v1.6.0.

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(/home/nre/Code/<redacted>/ansible.cfg) = True
COLLECTIONS_PATHS(/home/nre/Code/<redacted>/ansible.cfg) = ['/home/nre/Code/<redacted>/.ansible/collections', '/usr/share/ansible/collections']
DEFAULT_CALLBACK_WHITELIST(/home/nre/Code/<redacted>/ansible.cfg) = ['profile_tasks']
DEFAULT_FORKS(/home/nre/Code/<redacted>/ansible.cfg) = 50
DEFAULT_HOST_LIST(/home/nre/Code/<redacted>/ansible.cfg) = ['/home/nre/Code/<redacted>/ansible/playbooks/inventory']
DEFAULT_ROLES_PATH(/home/nre/Code/<redacted>/ansible.cfg) = ['/home/nre/Code/<redacted>/ansible/roles', '/home/nre/Code/<redacted>/.ansible/external_roles']
DEFAULT_VAULT_PASSWORD_FILE(/home/nre/Code/<redacted>/ansible.cfg) = /home/nre/Code/<redacted>/ansible/playbooks/vault/vault-password
HOST_KEY_CHECKING(/home/nre/Code/<redacted>/ansible.cfg) = False
INVENTORY_ENABLED(/home/nre/Code/<redacted>/ansible.cfg) = ['yaml']
RETRY_FILES_ENABLED(/home/nre/Code/<redacted>/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Pop!_OS 21.04

**Comment by jborean93** [comment]
You will need to grant the [SeServiceLogonRight](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/log-on-as-a-service) right for a user to be able to run as a service account. Potentially `nssm.exe` did this for you automatically but the workings of NSSM is not something I know much about.

You can use the [win_user_right](https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_user_right_module.html) module to do the same in Ansible:

```yaml
- win_user_right:
    name: SeServiceLogonRight
    action: add
    users:
    - MyAccount

**Comment by nre-ableton** [comment]
@jborean93 Thanks for the advice, I'll give that a try!
