### ISSUE TITLE
Request win_group (look for users in usergroup)

### ISSUE THREAD

**Issue by SchmidtJonathan1** [ansible-collections/community.windows#358]
##### SUMMARY

Hello community,
I edit the win_group module and add a new function, called query, to it. After the change its possible to display all user from a local windows usergroup. It's my first attempt to write a module, feel free to leave feedback or suggestions for improvement.

Thanks

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

win_group

##### ADDITIONAL INFORMATION

Run your task with state "query". It display users from a local windows usergroup. Output: Username + Class.

```powershell
    ElseIf($state -eq "query"){
        If (-not $check_mode){
            $result.results = @()
            ForEach ($groups In $group){
                $Members = @($group.psbase.Invoke("Members"))
                ForEach ($Member In $Members){
                    $Class = $Member.GetType().InvokeMember("Class", 'GetProperty', $Null, $Member, $Null)
                    $NameMember = $Member.GetType().InvokeMember("Name", 'GetProperty', $Null, $Member, $Null)
                    $result.results += @{"username"= $NameMember; "class"= $Class}
                }
            }
        }
        $result.changed = $true
    }
```

https://github.com/SchmidtJonathan1/Ansible_Module/blob/main/win_group_ADSI_new.ps1

**Comment by jborean93** [comment]
As per the README https://github.com/ansible-collections/community.windows#contributing-to-this-collection this collection is currently only accepting bugfixes or features to existing modules.
