### ISSUE TITLE
Windows BlockInfile

### ISSUE THREAD

**Issue by Tractorboy99** [ansible-collections/community.windows#364]
##### SUMMARY

Add support for blockinfile when deploying to windows
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

No Idea would guess something windows related

##### ADDITIONAL INFORMATION

Used in the same way as blockinfile, and would have saved my around 2 weeks of effort to find a component is os limited.

```yaml

```

**Comment by qx-dev** [comment]
+1 would be great!

**Comment by jborean93** [comment]
As per the README https://github.com/ansible-collections/community.windows#contributing-to-this-collection this collection is currently only accepting bugfixes or features to existing modules.

**Comment by msl0** [comment]
Hi @jborean93 Do you know why? Is there any other repo where we can add new modules for Windows OS?

**Comment by marwatk** [comment]
For anyone still looking, I had unsuccessfully attempted to [merge this functionality](https://github.com/ansible/ansible/pull/52586) back in 2019, and recently @randrej published it [here](https://galaxy.ansible.com/ui/repo/published/randrej/windows/) (source [here](https://github.com/randrej/randrej.windows))
