### ISSUE TITLE
win_chocolatey - add version constraints

### ISSUE THREAD

**Issue by jborean93** [ansible-collections/community.windows#39]
_From @mvorisek on Jun 16, 2019 13:18_

##### SUMMARY

I propose to add version range constraint support to accept versions like [7.3, 7.4).

Chocolatey has no native support, hovewer the Chocolatey can lookup all versions like `choco list php --by-id-only -a` (or with `-e switch once https://github.com/chocolatey/choco/issues/1843 is solved). So I propose to allow to specify version by version range constraint, find the latest stable version and then proceed with instal of the discovered/fixed version.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
win_chocolatey

_Copied from original issue: ansible/ansible#57917_

**Comment by jborean93** [comment]
Closing as the `win_chocolatey` module has been migrated to a Chocolatey specific collection [chocolatey.chocolatey](https://github.com/chocolatey/chocolatey-ansible).

cc @vexx32 just to be aware that this is not being tracked here anymore

**Comment by mvorisek** [comment]
@jborean93 Thanks for the ping, I migrated it.
