### ISSUE TITLE
no iso image

### ISSUE THREAD

**Issue by dgriffin51** [ansible-collections/community.windows#396]
I used the win 11 by pass, but it said no win iso image

**Comment by jborean93** [comment]
Please use the issue template provided, right it's hard to tell what the problem is. What's the module, what version of Ansible/collection are you using, what's the task, what's the full error when run with `-vvv`.

**Comment by dgriffin51** [comment]
![image](https://user-images.githubusercontent.com/103147171/168893942-a8756a03-2afc-481d-930b-54ddff51b6ec.png)
_ don't know if you can read this or not. _
