### ISSUE TITLE
Add Attribute SPN to win_domain_computer

### ISSUE THREAD

**Issue by deimosOmegaChan** [ansible-collections/community.windows#403]
##### SUMMARY

A new Attribute **spn** shall be added to manage **servicePrincipalName** of the module win_domain_computer.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

win_domain_computer

##### ADDITIONAL INFORMATION

This feature is needed to be able to setup kerberos authentication on no-windows systems.

```yaml

```

**Comment by jborean93** [comment]
The `win_domain_computer` module has been deprecated by https://github.com/ansible-collections/community.windows/pull/516 in favour of [microsoft.ad.computer](https://docs.ansible.com/ansible/devel/collections/microsoft/ad/computer_module.html#ansible-collections-microsoft-ad-computer-module). See the [migration guide](https://docs.ansible.com/ansible/devel/collections/microsoft/ad/docsite/guide_migration.html#module-win-domain-computer) for more info on how to change your code to use the newer module.

The `microsoft.ad.computer` module contains an `spn` option which can be used to add, remove, or set SPNs on a computer object.
