### ISSUE TITLE
Reconsider docsite links

### ISSUE THREAD

**Issue by samccann** [ansible-collections/community.windows#436]
##### SUMMARY

The current readme points to the main branch's module docs.  Since this shows up on Galaxy, it means the user is sent to docs that may not reflect the version that is in galaxy.

Options for this are:
 - replace the link in the readme with https://docs.ansible.com/ansible/devel/collections/community/windows/index.html#plugins-in-community-windows (the devel docs on docs.ansible.com always reflect what is latest in galaxy).
  - use an approach similar to https://github.com/ansible-collections/community.hashi_vault/#collection-documentation where it links to multiple versions of the module docs.

Another problem - the docsite link in the galaxy.yml doesn't currently point to anything useful. It could point to the github pages or docs.ansible.com rather than the docsite directory in the repo as it does today.

##### ISSUE TYPE
- Documentation Report

##### ANSIBLE VERSION

```paste below

```

**Comment by samccann** [comment]
More options from the DaWGs meeting:

the windows collection also have another option since they use stable branches
in the galaxy.yml for those "not latest" branches, they could point to the docsites built by the GH workflows for those branches
but I don't know how difficult that would be to manage
I don't think they've been published yet, but the workflows are set up to do so
or it could point to the tag docs builds, which will be built when the tag is pushed
etc.

**Comment by jborean93** [comment]
Links have been fixed in https://github.com/ansible-collections/community.windows/pull/441 based on the hashi_vault collection style.
