### ISSUE TITLE
win firewall module needed for allow an application like wmi, win RM for various firewall profile (Public, Private, Domain)

### ISSUE THREAD

**Issue by mchoudhury-tpr** [ansible-collections/community.windows#445]
I am looking for in firewall ansible module which can enable allow or prohibit specific application like WMI, Win RM etc..

**Comment by jborean93** [comment]
See [win_firewall_rule](https://docs.ansible.com/ansible/latest/collections/community/windows/win_firewall_rule_module.html). Please direct future questions to the mailing list or IRC as documented under

   * https://docs.ansible.com/ansible/latest/community/communication.html
