### ISSUE TITLE
CreateProcessW() failed (This version of %1 is not compatible with the version of Windows you're running) : Win32ErrorCode 216)\"", "rc": 2 

### ISSUE THREAD

**Issue by Akasurde** [ansible-collections/community.windows#52]
_From @hsvins12 on Mar 13, 2020 08:06_

##### SUMMARY
While executing the below commnd in  play book : 

win_command: C:/temp/HCL-OneTest-UI-Windows-x64-v10.0.2.0.exe -i silent -f C:\Temp\installer.properties

Getting the below error : 

<{"changed": false, "cmd": "C:/temp/HCL-OneTest-UI-Windows-x64-v10.0.2.0.exe -i silent -f C:\\Temp\\installer.properties", "msg": "Exception calling \"CreateProcess\" with \"5\" argument(s): \"CreateProcessW() failed (This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher, Win32ErrorCode 216)\"", "rc": 2}

##### ANSIBLE VERSION
ansible 2.9.5
config file = /etc/ansible/ansible.cfg

##### OS / ENVIRONMENT
MAC OS - High Siearra 10.13

_Copied from original issue: ansible/ansible#68206_

**Comment by Akasurde** [comment]
_From @Akasurde on Mar 17, 2020 08:42_

!component =lib/ansible/modules/windows/win_command.py

**Comment by ShachafGoldstein** [comment]
your system isn't 32 by any chance right?

**Comment by Akasurde** [comment]
cc @hsvins12

**Comment by jborean93** [comment]
This should be put in the `ansible.windows` repository as that is where win_command live now. In any case the error is that Windows is not able to run the executable specified which usually means you are trying to run a 64-bit executable in a 32-bit os or some other permutation of this. There is nothing we can do here and Windows is telling you that the executable is not valid for the version of Windows it is run on.
