### ISSUE TITLE
Unable to add user in AD group

### ISSUE THREAD

**Issue by ShyamKumar-Y** [ansible-collections/community.windows#526]
##### SUMMARY
Hi Team,

I`m unable to add the user in desired AD group. I`m unable to pass the domain password in secured way.
I`m using Anisble tower and stored the domain password in Vault in Ansible tower with name vault_domain_password. I`m not sure how to pass this password in the playbook. Here is my code,

- name: Add a domain user/group to a domain group using module win_domain_group_membership
          win_domain_group_membership:
             domain_server: "XXXXXXXX"
             domain_username: "svc_account"
             domain_password: "{{password}}"  <------------------------------------------------------------ Here how can I pass the password here? 
             name: "CN={{ var_grp }},OU={{ var_ou}} ,DC={{ var_dc1 }},DC={{ var_dc2 },DC=com"
             members:
                - shyamkumar
             state: present 
          register: group_result

Is there any variable I need to define for domain password in either in the job template or in the playbook?

Please advise here. Your help is much appreciated. 
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_domain_group_membership

##### ANSIBLE VERSION
Ansible 2.9.27

```

##### COLLECTION VERSION
<!--- Paste verbatim output from "ansible-galaxy collection list <namespace>.<collection>"  between the quotes
for example: ansible-galaxy collection list community.general
-->
```paste below

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT
RHEL 8

##### STEPS TO REPRODUCE

```yaml

```

##### EXPECTED RESULTS
It should add the user in desired group which is defined as variable {{ var_grp }}

##### ACTUAL RESULTS
It should add the user in desired group which is defined as variable {{ var_grp }}

```

**Comment by jborean93** [comment]
This module is deprecated in favour of [microsoft.ad.group](https://docs.ansible.com/ansible/latest/collections/microsoft/ad/group_module.html). In terms of the username/password, this can be stored in any location you like with Ansible. As long as it's a var available to the play you can template it with the module.
